version: '3.8'

services:
  api:
    build:
      target: production
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  db:
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M